### ISSUE TITLE
gan minta folder vendornya

### ISSUE THREAD

**Issue by panwaskdb** [FajarAdiSetyawan/Company-Profile#1]
minta vendor nya gan

**Comment by FajarAdiSetyawan** [comment]
sudah diupdate ya gan, di ekstrak aja rar vendornya

**Comment by panwaskdb** [comment]
thank gan

**Comment by panwaskdb** [comment]
untuk akses hal admin url e gmna yah

**Comment by FajarAdiSetyawan** [comment]
> untuk akses hal admin url e gmna yah

/company-profile/auth

**Comment by azaisan** [comment]
terima kasih gan

Pada tanggal Rab, 11 Jan 2023 14.00, Fajar Adi Setyawan <
***@***.***> menulis:
